language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  global:
    - PYTHONWARNINGS="default,ignore::PendingDeprecationWarning,ignore::ResourceWarning"
  matrix:
    - DB="POSTGRESQL"
    - DB="MYSQL"

sudo: false

cache: pip

addons:
  postgresql: "9.3"
  mysql: "5.5"

before_install:
  - pip install codecov
  - pip install -e git+https://github.com/modoboa/modoboa.git#egg=modoboa

install:
  - pip install -q -r requirements.txt
  - pip install -q -r test-requirements.txt
  - python setup.py -q develop
  - nvm install 6.10
  - cd frontend
  - npm install

script:
  - npm run unit
  - cd ../test_project
  - coverage run --source ../modoboa_contacts manage.py test modoboa_contacts

after_success:
  - cd ../frontend
  - codecov
  - cd ../test_project
  - codecov
