language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DB="POSTGRESQL"
  - DB="MYSQL"

services:
  - mysql
  - postgresql

before_install:
  - if [[ $DB = 'POSTGRESQL' ]]; then pip install -q psycopg2; fi
  - if [[ $DB = 'MYSQL' ]]; then pip install -q mysqlclient; fi

install:
  - pip install codecov
  - pip install -e git+https://github.com/modoboa/modoboa.git#egg=modoboa
  - pip install -q -r test-requirements.txt
  - python setup.py -q develop
  - nvm install 6.10
  - cd frontend
  - npm install

before_script:
  - if [[ $DB = 'POSTGRESQL' ]]; then psql -c 'create database modoboa_test;' -U postgres; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "create database IF NOT EXISTS modoboa_test;" -uroot; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "CREATE USER 'modoboa'@'localhost' IDENTIFIED BY 'modoboa'" -uroot; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'modoboa'@'localhost';" -uroot; fi

script:
  - npm run unit
  - cd ../test_project
  - coverage run --source ../modoboa_contacts manage.py test modoboa_contacts

after_success:
  - cd ../frontend
  - codecov
  - cd ../test_project
  - codecov
